# Generated by Django 4.2.7 on 2024-05-11 10:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='商品',
            fields=[
                ('商品編號', models.AutoField(primary_key=True, serialize=False)),
                ('分類', models.CharField(max_length=50)),
                ('名稱', models.CharField(max_length=100)),
                ('商品介紹', models.TextField()),
                ('圖片', models.CharField(max_length=255)),
                ('價格', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='會員資料',
            fields=[
                ('會員編號', models.AutoField(primary_key=True, serialize=False)),
                ('姓名', models.CharField(max_length=50)),
                ('生日', models.DateField()),
                ('性別', models.CharField(choices=[('男', '男'), ('女', '女')], max_length=1)),
                ('電話號碼', models.CharField(max_length=20)),
                ('電子郵件', models.EmailField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='訂單',
            fields=[
                ('訂單編號', models.AutoField(primary_key=True, serialize=False)),
                ('下單日期', models.DateField()),
                ('付款方式', models.CharField(choices=[('信用卡', '信用卡'), ('貨到付款', '貨到付款'), ('轉帳', '轉帳')], max_length=10)),
                ('金額', models.PositiveIntegerField()),
                ('訂單狀態', models.CharField(choices=[('已接受訂單', '已接受訂單'), ('包貨中', '包貨中'), ('出貨中', '出貨中'), ('物流中心', '物流中心')], max_length=10)),
                ('送貨地址', models.CharField(max_length=100)),
                ('會員編號', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.會員資料')),
            ],
        ),
        migrations.CreateModel(
            name='會員密碼',
            fields=[
                ('會員編號', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.會員資料')),
                ('密碼', models.CharField(default='your_default_password', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='購物車',
            fields=[
                ('購物車編號', models.AutoField(primary_key=True, serialize=False)),
                ('尺寸', models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('F', 'F')], max_length=1)),
                ('數量', models.PositiveIntegerField()),
                ('商品編號', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.商品')),
                ('會員編號', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.會員資料')),
            ],
        ),
        migrations.CreateModel(
            name='評論',
            fields=[
                ('評論編號', models.AutoField(primary_key=True, serialize=False)),
                ('評分', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('留言', models.TextField()),
                ('評分日期', models.DateField()),
                ('商品編號', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.商品')),
                ('會員編號', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.會員資料')),
                ('訂單編號', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.訂單')),
            ],
        ),
        migrations.CreateModel(
            name='訂單明細',
            fields=[
                ('訂單明細編號', models.AutoField(primary_key=True, serialize=False)),
                ('尺寸', models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('F', 'F')], max_length=1)),
                ('數量', models.PositiveIntegerField()),
                ('價錢', models.PositiveIntegerField()),
                ('商品編號', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.商品')),
                ('訂單編號', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.訂單')),
            ],
        ),
        migrations.CreateModel(
            name='庫存',
            fields=[
                ('庫存編號', models.AutoField(primary_key=True, serialize=False)),
                ('尺寸', models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('F', 'F')], default='S', max_length=1)),
                ('數量', models.PositiveIntegerField()),
                ('商品編號', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.商品')),
            ],
        ),
    ]
