# Generated by Django 4.2.4 on 2024-05-15 05:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('commentNo', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('message', models.TextField()),
                ('commentDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='MemberData',
            fields=[
                ('menberNo', models.AutoField(primary_key=True, serialize=False)),
                ('menberName', models.CharField(max_length=50)),
                ('birthday', models.DateField()),
                ('性別', models.CharField(choices=[('男', '男'), ('女', '女')], max_length=1)),
                ('gender', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderNo', models.AutoField(primary_key=True, serialize=False)),
                ('orderdate', models.DateField()),
                ('pay', models.CharField(choices=[('信用卡', '信用卡'), ('貨到付款', '貨到付款'), ('轉帳', '轉帳')], max_length=10)),
                ('total', models.PositiveIntegerField()),
                ('orderStatus', models.CharField(choices=[('已接受訂單', '已接受訂單'), ('包貨中', '包貨中'), ('出貨中', '出貨中'), ('物流中心', '物流中心')], max_length=10)),
                ('address', models.CharField(max_length=100)),
                ('menberNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.memberdata')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('orderdetailNo', models.AutoField(primary_key=True, serialize=False)),
                ('size', models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('F', 'F')], max_length=1)),
                ('quantity', models.PositiveIntegerField()),
                ('singlePrice', models.PositiveIntegerField()),
                ('orderNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.order')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productNo', models.AutoField(primary_key=True, serialize=False)),
                ('classification', models.CharField(max_length=50)),
                ('productName', models.CharField(max_length=100)),
                ('describe', models.TextField()),
                ('picture', models.CharField(max_length=255)),
                ('price', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ShopingCart',
            fields=[
                ('shopingcartNo', models.AutoField(primary_key=True, serialize=False)),
                ('size', models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('F', 'F')], max_length=1)),
                ('quantity', models.PositiveIntegerField()),
                ('menberNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.memberdata')),
                ('productNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.product')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('storeNo', models.AutoField(primary_key=True, serialize=False)),
                ('size', models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('F', 'F')], default='S', max_length=1)),
                ('quantity', models.PositiveIntegerField()),
                ('productNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.product')),
            ],
        ),
        migrations.RemoveField(
            model_name='庫存',
            name='商品編號',
        ),
        migrations.RemoveField(
            model_name='會員密碼',
            name='會員編號',
        ),
        migrations.RemoveField(
            model_name='訂單',
            name='會員編號',
        ),
        migrations.RemoveField(
            model_name='訂單明細',
            name='商品編號',
        ),
        migrations.RemoveField(
            model_name='訂單明細',
            name='訂單編號',
        ),
        migrations.RemoveField(
            model_name='評論',
            name='商品編號',
        ),
        migrations.RemoveField(
            model_name='評論',
            name='會員編號',
        ),
        migrations.RemoveField(
            model_name='評論',
            name='訂單編號',
        ),
        migrations.RemoveField(
            model_name='購物車',
            name='商品編號',
        ),
        migrations.RemoveField(
            model_name='購物車',
            name='會員編號',
        ),
        migrations.CreateModel(
            name='MemberPassword',
            fields=[
                ('menberNo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.memberdata')),
                ('password', models.CharField(default='your_default_password', max_length=128)),
            ],
        ),
        migrations.DeleteModel(
            name='商品',
        ),
        migrations.DeleteModel(
            name='庫存',
        ),
        migrations.DeleteModel(
            name='會員密碼',
        ),
        migrations.DeleteModel(
            name='會員資料',
        ),
        migrations.DeleteModel(
            name='訂單',
        ),
        migrations.DeleteModel(
            name='訂單明細',
        ),
        migrations.DeleteModel(
            name='評論',
        ),
        migrations.DeleteModel(
            name='購物車',
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='productNo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.product'),
        ),
        migrations.AddField(
            model_name='comment',
            name='memberNo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.memberdata'),
        ),
        migrations.AddField(
            model_name='comment',
            name='orderNo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.order'),
        ),
        migrations.AddField(
            model_name='comment',
            name='productNo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.product'),
        ),
    ]
