# Generated by Django 4.2.4 on 2024-05-15 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_comment_memberdata_order_orderdetail_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberdata',
            name='性別',
        ),
        migrations.AddField(
            model_name='memberdata',
            name='phone',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='memberdata',
            name='gender',
            field=models.CharField(choices=[('男', '男'), ('女', '女')], max_length=1),
        ),
    ]
