# Generated by Django 4.2.7 on 2024-05-23 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_memberdata_性別_memberdata_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='commentDate',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='memberdata',
            name='phone',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='memberpassword',
            name='password',
            field=models.CharField(default='your_default_password', max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderdate',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='size',
            field=models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='productNo',
            field=models.CharField(max_length=5, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='shopingcart',
            name='size',
            field=models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('F', 'F')], max_length=2),
        ),
    ]
