# Generated by Django 4.2.7 on 2024-05-23 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_comment_commentdate_alter_memberdata_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='classification',
        ),
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='productNo',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
