# Generated by Django 4.2.7 on 2024-05-23 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_product_classification_alter_product_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderStatus',
            field=models.CharField(default='已接受訂單', editable=False, max_length=5),
        ),
    ]
