# Generated by Django 4.2.7 on 2024-05-23 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_order_orderstatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memberdata',
            old_name='menberName',
            new_name='memberName',
        ),
        migrations.RenameField(
            model_name='memberdata',
            old_name='menberNo',
            new_name='memberNo',
        ),
        migrations.AddField(
            model_name='memberdata',
            name='password',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.DeleteModel(
            name='MemberPassword',
        ),
    ]
