# Generated by Django 4.2.6 on 2024-05-24 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='CustomUser',
        ),
    ]
