# Generated by Django 4.2.7 on 2024-05-30 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_rename_user_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('tops', '上衣'), ('bottoms', '下装'), ('dresses', '洋装'), ('sweaters', '毛衣'), ('outerwear', '外套/夾克'), ('homewear', '家居'), ('shoes', '鞋子'), ('bags', '包包'), ('accessories', '配件')], default='上衣', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.CharField(default='上衣', max_length=50),
        ),
    ]
