# Generated by Django 4.2.7 on 2024-05-30 12:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_post_delete_customuser_alter_memberdata_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='commentDate',
            field=models.DateField(auto_now_add=True, verbose_name='評論日期'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='commentNo',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='評論編號'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='memberNo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.memberdata', verbose_name='會員編號'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='message',
            field=models.TextField(verbose_name='評論內容'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='orderNo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.order', verbose_name='訂單編號'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='productNo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.product', verbose_name='商品編號'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='score',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='評分'),
        ),
        migrations.AlterField(
            model_name='memberdata',
            name='birthday',
            field=models.DateField(verbose_name='生日'),
        ),
        migrations.AlterField(
            model_name='memberdata',
            name='email',
            field=models.EmailField(max_length=100, verbose_name='電子郵件'),
        ),
        migrations.AlterField(
            model_name='memberdata',
            name='gender',
            field=models.CharField(choices=[('男', '男'), ('女', '女')], max_length=1, verbose_name='性別'),
        ),
        migrations.AlterField(
            model_name='memberdata',
            name='memberName',
            field=models.CharField(max_length=50, verbose_name='會員姓名'),
        ),
        migrations.AlterField(
            model_name='memberdata',
            name='memberNo',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='會員編號'),
        ),
        migrations.AlterField(
            model_name='memberdata',
            name='password',
            field=models.CharField(default='', max_length=100, verbose_name='密碼'),
        ),
        migrations.AlterField(
            model_name='memberdata',
            name='phone',
            field=models.CharField(default='', max_length=20, verbose_name='電話'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=100, verbose_name='寄送地址'),
        ),
        migrations.AlterField(
            model_name='order',
            name='menberNo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.memberdata', verbose_name='會員編號'),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderNo',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='訂單編號'),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderStatus',
            field=models.CharField(default='已接受訂單', editable=False, max_length=5, verbose_name='訂單狀態'),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderdate',
            field=models.DateField(auto_now_add=True, verbose_name='訂單日期'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pay',
            field=models.CharField(choices=[('信用卡', '信用卡'), ('貨到付款', '貨到付款'), ('轉帳', '轉帳')], max_length=10, verbose_name='付款方式'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.PositiveIntegerField(verbose_name='總金額'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='orderNo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.order', verbose_name='訂單編號'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='orderdetailNo',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='訂單明細編號'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='productNo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.product', verbose_name='商品編號'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='數量'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='singlePrice',
            field=models.PositiveIntegerField(verbose_name='單價'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='size',
            field=models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], max_length=2, verbose_name='尺寸'),
        ),
        migrations.AlterField(
            model_name='post',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='電子郵件'),
        ),
        migrations.AlterField(
            model_name='post',
            name='password',
            field=models.CharField(max_length=100, verbose_name='密碼'),
        ),
        migrations.AlterField(
            model_name='post',
            name='username',
            field=models.CharField(max_length=100, verbose_name='用戶名稱'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('tops', '上衣'), ('bottoms', '下装'), ('dresses', '洋装'), ('sweaters', '毛衣'), ('outerwear', '外套/夾克'), ('homewear', '家居'), ('shoes', '鞋子'), ('bags', '包包'), ('accessories', '配件')], default='tops', max_length=50, verbose_name='商品類別'),
        ),
        migrations.AlterField(
            model_name='product',
            name='describe',
            field=models.TextField(verbose_name='商品描述'),
        ),
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.URLField(verbose_name='圖片'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='價格'),
        ),
        migrations.AlterField(
            model_name='product',
            name='productName',
            field=models.CharField(max_length=100, verbose_name='商品名稱'),
        ),
        migrations.AlterField(
            model_name='product',
            name='productNo',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='商品編號'),
        ),
        migrations.AlterField(
            model_name='product',
            name='subcategory',
            field=models.CharField(default='sleeveless', max_length=50, verbose_name='商品子類別'),
        ),
        migrations.AlterField(
            model_name='shopingcart',
            name='menberNo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.memberdata', verbose_name='會員編號'),
        ),
        migrations.AlterField(
            model_name='shopingcart',
            name='productNo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.product', verbose_name='商品編號'),
        ),
        migrations.AlterField(
            model_name='shopingcart',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='數量'),
        ),
        migrations.AlterField(
            model_name='shopingcart',
            name='shopingcartNo',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='購物車編號'),
        ),
        migrations.AlterField(
            model_name='shopingcart',
            name='size',
            field=models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('F', 'F')], max_length=2, verbose_name='尺寸'),
        ),
        migrations.AlterField(
            model_name='store',
            name='productNo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.product', verbose_name='商品編號'),
        ),
        migrations.AlterField(
            model_name='store',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='數量'),
        ),
        migrations.AlterField(
            model_name='store',
            name='size',
            field=models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('F', 'F')], default='S', max_length=1, verbose_name='尺寸'),
        ),
        migrations.AlterField(
            model_name='store',
            name='storeNo',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='店舖編號'),
        ),
    ]
