# Generated by Django 4.2.7 on 2024-05-30 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_comment_commentdate_alter_comment_commentno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopingcart',
            name='size',
            field=models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], max_length=2, verbose_name='尺寸'),
        ),
        migrations.AlterField(
            model_name='store',
            name='size',
            field=models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], default='S', max_length=2, verbose_name='尺寸'),
        ),
    ]
