# Generated by Django 4.2.7 on 2024-05-31 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_shopingcart_size_alter_store_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='size',
            field=models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('F', 'F')], max_length=2, verbose_name='尺寸'),
        ),
        migrations.AlterField(
            model_name='shopingcart',
            name='size',
            field=models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('F', 'F')], max_length=2, verbose_name='尺寸'),
        ),
        migrations.AlterField(
            model_name='store',
            name='size',
            field=models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('F', 'F')], default='S', max_length=2, verbose_name='尺寸'),
        ),
        migrations.AlterField(
            model_name='store',
            name='storeNo',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='庫存編號'),
        ),
    ]
