# Generated by Django 4.2.5 on 2024-06-09 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0015_memberdata_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderdetail",
            name="picture",
            field=models.URLField(blank=True, null=True, verbose_name="圖片"),
        ),
        migrations.AddField(
            model_name="orderdetail",
            name="productName",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="商品名稱"
            ),
        ),
        migrations.AddField(
            model_name="shopingcart",
            name="picture",
            field=models.URLField(blank=True, null=True, verbose_name="圖片"),
        ),
        migrations.AddField(
            model_name="shopingcart",
            name="price",
            field=models.PositiveIntegerField(default=0, verbose_name="價格"),
        ),
        migrations.AddField(
            model_name="shopingcart",
            name="productName",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="商品名稱"
            ),
        ),
    ]
